//cerne010 and shahx252
public class Port{

    public String name;
    public int[] location;
    private int portID; //easy way to get port ID 0 = Minneapolis, 1 = St. Paul, etc
    private int shipPerDay;
    private Q2 portQueue = new Q2(); //queue of shipments in the port generated by ShipmentMaker
    private int x, y; //x and y coordinates of ports
    public static int maxLine;
    public static double avgline;

    public int getShipPerDay(){
        return shipPerDay;
    }

    public Q2 getQ2(){
        return portQueue;
    }

    public int getPortID(){
        return portID;
    }

    public String toString(){
        return name;
    }
    public Port(String name, int[] location){
        this.name = name;
        this.location = location;
        switch (name){ //each port has different stats. This sets them based on
            case "Minneapolis":// the name passed into the object constructor.
                shipPerDay = 50;
                portID = 0;
                x = 0;
                y = 0;
                break;
            case "Saint Paul":
                shipPerDay = 50;
                portID = 1;
                x = 0;
                y = 10;
                break;
            case "Antartica":
                shipPerDay = 10;
                portID = 2;
                x = 0;
                y = -6000;
                break;
            case "Japan":
                shipPerDay = 100;
                portID = 3;
                x = 4000;
                y = 4000;
                break;
            case "Korea":
                shipPerDay = 50;
                portID = 4;
                x = 6000;
                y = 5000;
                break;
            case "China":
                shipPerDay = 1000;
                portID = 5;
                x = 5000;
                y = 6000;
                break;
            case "Moon":
                shipPerDay = 0;
                portID = 6;
                x = 0;
                y = 1000000;
                break;
            case "Panama":
                shipPerDay = 50;
                portID = 7;
                x = 1000;
                y = 3000;
                break;
            case "Hawaii":
                shipPerDay = 50;
                portID = 8;
                x = 2000;
                y = 2000;
                break;
            case "Pirate Town":
                shipPerDay = 100;
                portID = 9;
                x = 3000;
                y = 3000;
                break;
            default:
                shipPerDay = -1;
                portID = -1;
                x = -1;
                y = -1;
                break;
        }

    }

}